//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIPDC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public Bank()
        {
            this.ConfirmationLetters = new HashSet<ConfirmationLetter>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public System.DateTime CreatedWhen { get; set; }
        public string CreatedWho { get; set; }
        public System.DateTime ChangedWhen { get; set; }
        public string ChangedWho { get; set; }
    
        public virtual ICollection<ConfirmationLetter> ConfirmationLetters { get; set; }
    }
}
