//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIPDC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfirmationLetter
    {
        public ConfirmationLetter()
        {
            this.ConfirmationLetter1 = new HashSet<ConfirmationLetter>();
            this.ConfirmationLetterSchedules = new HashSet<ConfirmationLetterSchedule>();
            this.Modules = new HashSet<Module>();
            this.Customers = new HashSet<Customer>();
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int ID { get; set; }
        public string LetterNo { get; set; }
        public System.DateTime Date { get; set; }
        public int AccountManagerID { get; set; }
        public int CustomerID { get; set; }
        public string TrainingLocation { get; set; }
        public string Description { get; set; }
        public Nullable<int> TransferToBankID { get; set; }
        public int TotalParticipants { get; set; }
        public int ClassTypeID { get; set; }
        public int TopicID { get; set; }
        public decimal Price { get; set; }
        public decimal Tax { get; set; }
        public decimal PPH { get; set; }
        public decimal Discount { get; set; }
        public decimal TotalPrice { get; set; }
        public Nullable<System.DateTime> PaymentDueDate { get; set; }
        public Nullable<System.DateTime> LetterReceiveDate { get; set; }
        public Nullable<int> RefLetterID { get; set; }
        public System.DateTime CreatedWhen { get; set; }
        public string CreatedWho { get; set; }
        public System.DateTime ChangedWhen { get; set; }
        public string ChangedWho { get; set; }
        public Nullable<System.DateTime> VoidDate { get; set; }
        public string VoidReason { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual ClassType ClassType { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<ConfirmationLetter> ConfirmationLetter1 { get; set; }
        public virtual ConfirmationLetter ConfirmationLetter2 { get; set; }
        public virtual Topic Topic { get; set; }
        public virtual ICollection<ConfirmationLetterSchedule> ConfirmationLetterSchedules { get; set; }
        public virtual ICollection<Module> Modules { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
