//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIPDC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Alerts = new HashSet<Alert>();
            this.ConfirmationLetters = new HashSet<ConfirmationLetter>();
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string CellPhone1 { get; set; }
        public string CellPhone2 { get; set; }
        public string Email { get; set; }
        public int RoleID { get; set; }
        public bool IsAllowLogin { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime ChangedWhen { get; set; }
        public string ChangedWho { get; set; }
        public System.DateTime CreatedWhen { get; set; }
        public string CreatedWho { get; set; }
        public string Initial { get; set; }
        public bool IsAllowBackdate { get; set; }
        public Nullable<int> BackColor { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ICollection<Alert> Alerts { get; set; }
        public virtual ICollection<ConfirmationLetter> ConfirmationLetters { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
