//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIPDC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int ID { get; set; }
        public int LetterID { get; set; }
        public string InvoiceNo { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Price { get; set; }
        public decimal Tax { get; set; }
        public decimal PPH { get; set; }
        public decimal Discount { get; set; }
        public decimal TotalPrice { get; set; }
        public Nullable<int> TransferToBankID { get; set; }
        public System.DateTime PaymentDueDate { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> VoidDate { get; set; }
        public string VoidReason { get; set; }
        public Nullable<System.DateTime> CreatedWhen { get; set; }
        public string CreatedWho { get; set; }
        public Nullable<System.DateTime> ChangedWhen { get; set; }
        public string ChangedWho { get; set; }
    
        public virtual ConfirmationLetter ConfirmationLetter { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
