//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIPDC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int ID { get; set; }
        public int InvoiceID { get; set; }
        public string PaymentType { get; set; }
        public System.DateTime Date { get; set; }
        public string ApprovalCode { get; set; }
        public decimal Amount { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> VoidDate { get; set; }
        public string VoidReason { get; set; }
        public System.DateTime CreatedWhen { get; set; }
        public string CreatedWho { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
