//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIPDC.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VIPDCEntities : DbContext
    {
        public VIPDCEntities()
            : base("name=VIPDCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ClassType> ClassTypes { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<JobPosition> JobPositions { get; set; }
        public DbSet<Menu> Menus { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<RoleMenu> RoleMenus { get; set; }
        public DbSet<RunningNumber> RunningNumbers { get; set; }
        public DbSet<Topic> Topics { get; set; }
        public DbSet<MenuType> MenuTypes { get; set; }
        public DbSet<Module> Modules { get; set; }
        public DbSet<Payment> Payments { get; set; }
        public DbSet<Configuration> Configurations { get; set; }
        public DbSet<Alert> Alerts { get; set; }
        public DbSet<Bank> Banks { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<InformationSource> InformationSources { get; set; }
        public DbSet<ConfirmationLetter> ConfirmationLetters { get; set; }
        public DbSet<ConfirmationLetterSchedule> ConfirmationLetterSchedules { get; set; }
        public DbSet<Invoice> Invoices { get; set; }
    }
}
